/**
 * Employee claim submission API route.
 *
 * Accepts a POST request containing claim form data and delegates
 * creation to the DataManager helper.
 *
 * Returns the response generated by createClaim() or a 500 error.
 *
 * @param {NextRequest} request - Incoming POST request with claim payload.
 * @returns {Promise<Response>} JSON response from claim creation or error.
 */
import { NextRequest, NextResponse } from "next/server";
import { createClaim } from "@/tools/DataManager";

export async function POST(request: NextRequest) {
    try {
        const response = await createClaim(request);
        return response;
    } catch (error: any) {
        return NextResponse.json(
            { error: error.message },
            { status: 500 }
        );
    }
}